---
title: "Fig. 1"
author: "Heather Wheeler"
date: "`r Sys.time()`"
output: html_document
---

### R code for Figures in Mogil et al. "Genetic architecture of gene expression traits across diverse populations" <https://doi.org/10.1101/245761>
- Revision 1, submitted June 1, 2018

```{r}
library(dplyr)
library(ggplot2)
library(gridExtra)
library(data.table)
library(viridis)
library(tidyr)

"%&%" = function(a,b) paste(a,b,sep="")
```

### Fig 1
```{r,fig.width=8,fig.height=3}
my.dir = "/home/lauren/files_for_revisions_plosgen/meqtl_results/"
#read in pi1
for(nk in c(0,10,20,30)){
  a <- read.table(my.dir %&% "pi1_nk" %&% nk %&% "_pc3.txt",header=T) %>% dplyr::mutate(nk=nk)
  if(exists('res')){
    res <- rbind(res, a)
  }else{
    res <- a
  }
}
colnames(res) <- c("disc_pop","FHS","MXL","YRI","GEU", "nk")
res_g <- tidyr::gather(res,rep_pop,pi1,-disc_pop,-nk)
res_g <- mutate(res_g, disc_pop=factor(disc_pop,levels=c('ALL','AFHI','HIS','CAU','AFA')))
res_gr <- mutate(res_g, disc_pop=factor(disc_pop,levels=c('AFA','CAU','HIS','AFHI','ALL')))

res_g3 <- dplyr::filter(res_gr, disc_pop != 'AFHI' & disc_pop != 'ALL')

fig <- ggplot(res_g3, aes(x=nk,y=pi1,col=rep_pop)) + geom_line() + geom_point() + facet_wrap(~disc_pop) +
  scale_color_viridis(discrete = TRUE) + theme_bw(14) + labs(x="Number of Peer Factors",y=expression(pi[1]),col="Replication\nPopulation")
print(fig)

tiff("Fig1.tiff", width = 8, height = 3, units = 'in', res = 300, compression = 'lzw')
fig
dev.off()
```