---
title: "Fig. 2"
author: "Heather Wheeler"
date: "`r Sys.time()`"
output: html_document
---

### R code for Figures in Mogil et al. "Genetic architecture of gene expression traits across diverse populations" <https://doi.org/10.1101/245761>
- Revision 1, submitted June 1, 2018
- Figure 2
- Table 2

```{r}
library(dplyr)
library(ggplot2)
library(gridExtra)
library(data.table)
library(viridis)
library(tidyr)
library(xtable)

"%&%" = function(a,b) paste(a,b,sep="")
```

### Fig 2
```{r,fig.width=8,fig.height=3}
my.dir <- "/home/wheelerlab3/mesa_analyses/"
for(pop in c('AFA-CAU','AFA-HIS','CAU-HIS')){
  obs <- fread(my.dir %&% "GCTA_exp/" %&% pop %&% "_MESA_Nk-20.local-h2_gen-corr_UMich_imp.2018-05-03.txt") %>% 
    dplyr::mutate(data="obs " %&% pop)
  if(exists('sims')){
    sims <- rbind(sims, obs)
  }else{
    sims <- obs
  }
  for(i in c(0:9)){
    a <- fread(my.dir %&% "GCTA_exp/" %&% pop %&% "_MESA_Nk-20.local-h2_gen-corr_EXP-SIM-" %&% i %&% "_UMich_imp.2018-05-03.txt") %>% dplyr::mutate(data="sim " %&% pop)
    sims <- rbind(sims, a)
  }
}

sims <- mutate(sims,data=ifelse(data=='obs CAU-HIS','obs HIS-CAU',data))
sims <- mutate(sims,data=ifelse(data=='sim CAU-HIS','sim HIS-CAU',data))

c <- ggplot(sims,aes(x=data,y=rG)) + geom_violin() + stat_summary(fun.y=mean, geom="point", color="blue", size=3) +
        labs(x="",title="C") + theme_bw(14)

simsdt <- data.table(sims)
simsdt[,list(mean=mean(rG,na.rm=TRUE),se=sd(rG,na.rm=TRUE)/sqrt(length(rG[!is.na(rG)])),converged=length(rG[!is.na(rG)])),by='data']

for(pop in c('AFA-CAU','AFA-HIS','CAU-HIS')){
  pres <- read.table(my.dir %&% "GCTA_exp/" %&% pop %&% "_MESA_Nk-20.local-h2_gen-corr_UMich_imp.2018-05-03_with_SNP_count.txt",header=T)
  pres <- dplyr::mutate(pres,min.h2=ifelse(pop1.h2<pop2.h2,pop1.h2,pop2.h2), max.h2=ifelse(pop1.h2>pop2.h2,pop1.h2,pop2.h2), pop=pop)
  if(exists('res')){
    res <- rbind(res, data.frame(pres))
  }else{
    res <- data.frame(pres)
  }
}

res <- mutate(res,pop=ifelse(pop=="CAU-HIS","HIS-CAU",pop))

#Table 2 Stats
resdt <- data.table(res)
tab2 <- resdt[,list(mean=mean(rG,na.rm=TRUE),se=sd(rG,na.rm=TRUE)/sqrt(length(rG[!is.na(rG)])),converged=length(rG[!is.na(rG)])),by='pop']
print(tab2)
xtable(tab2)


a <- ggplot(res, aes(x=rG,y=min.h2,col=max.h2)) + geom_point() +
  coord_cartesian(xlim=c(-1,1)) + facet_wrap(~pop)  + 
  theme_bw(14) +  labs(col=expression(paste("max ",h^2)),y=expression(paste("min ", h^2)),title="A") + 
  theme(legend.justification=c(0,1), legend.position=c(0.005,0.995),legend.title = element_text(size=8),legend.text = element_text(size=8),legend.key.size = unit(0.2, "cm"))


#Comparison of the genetic correlation between pairwise MESA populations and the subset of genes with heritability (h\textsuperscript{2}) greater than a given threshold in AFA

calc_mean <- function(df, h2, poppair){
  subres <- dplyr::filter(df, pop=='AFA-CAU', pop1.h2 >= h2)
  popres <- dplyr::filter(df, pop==poppair, ensid %in% subres$ensid)
  mean_rG <- mean(popres$rG, na.rm=TRUE)
  return(mean_rG)
}

for(poppair in c("AFA-CAU", "AFA-HIS", "HIS-CAU")){
  for(afah2 in c(0:16/20)){
    m <- calc_mean(res, afah2, poppair)
    r <- data.frame(poppair, afah2, m)
    if(exists('toplot')){
      toplot <- rbind(toplot, r)
    }else{
      toplot <- r
    }
  }
}
colnames(toplot) <- c("pop", "h2", "mean_rG")

b <- ggplot(toplot, aes(x=h2,y=mean_rG,col=pop)) + geom_smooth() + scale_color_viridis(discrete=TRUE) +
  labs(x=expression(paste(h^2, " threshold in AFA")),y="mean rG",col="pop pair",title="B") +
  theme_bw(14)
```

```{r, fig.width=8,fig.height=10}
grid.arrange(a,b,c,nrow=3)
```

```{r}
tiff("Fig2.tiff", width = 8, height = 10, units = 'in', res = 300, compression = 'lzw')
grid.arrange(a,b,c,nrow=3)
dev.off()
```